import { useState } from "react";
import { Bell, CalendarDays, ChevronRight, Clock3, Heart, Home, MapPin, MessageCircle, Search, Sparkles, UserRound, Zap } from "lucide-react";

const professionals = [
  { name: "Lucas Barbeiro", handle: "@lucasfade", specialty: "Fade & visagismo", distance: "0,8 km", wait: "15 min", status: "available", image: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=900&q=85" },
  { name: "Studio Navalha", handle: "@studionavalha", specialty: "Corte clássico", distance: "1,4 km", wait: "Atendendo", status: "busy", image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=85" },
];

const status: Record<string, { label: string; className: string }> = {
  available: { label: "Disponível agora", className: "text-emerald-300 bg-emerald-400/10" },
  busy: { label: "Atendendo · 25 min", className: "text-amber-200 bg-amber-300/10" },
};

export function EliteClientApp() {
  const [active, setActive] = useState("início");
  const [liked, setLiked] = useState<number[]>([]);
  return <main className="elite-shell min-h-screen pb-28 text-white">
    <header className="flex items-center justify-between px-5 pb-5 pt-8"><div><p className="elite-kicker">Sua experiência, elevada</p><h1 className="mt-1 text-3xl font-black tracking-[-0.07em]">Olá, Gabriel<span className="text-[#c6ff4a]">.</span></h1><div className="mt-2 flex items-center gap-1.5 text-xs text-white/45"><MapPin size={13} className="text-[#c6ff4a]"/> Vila Madalena, São Paulo <ChevronRight size={13}/></div></div><button aria-label="Notificações" className="elite-icon"><Bell size={18}/><span/></button></header>
    <section className="flex gap-3 overflow-x-auto px-5 pb-6 [scrollbar-width:none]">
      {[{label:"Perto de mim", image:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80"},{label:"Mais bem avaliados", image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80"},{label:"Novidades", image:"https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80"}].map((story) => <button key={story.label} className="shrink-0 text-center"><div className="story-ring"><img src={story.image} alt=""/></div><span className="mt-2 block text-[11px] text-white/60">{story.label}</span></button>)}
    </section>
    <section className="px-5"><div className="elite-search"><Search size={17}/><span>Buscar profissionais, serviços...</span><button aria-label="Filtros" className="ml-auto rounded-xl bg-white/10 p-2"><Sparkles size={15}/></button></div></section>
    <section className="mt-7"><div className="flex items-end justify-between px-5"><div><p className="elite-kicker text-[#c6ff4a]">Agora perto de você</p><h2 className="mt-1 text-xl font-bold tracking-tight">Encontre seu próximo visual</h2></div><button className="text-xs font-semibold text-white/45">Ver mapa</button></div><div className="mt-4 flex gap-4 overflow-x-auto px-5 pb-2 [scrollbar-width:none]">{professionals.map((pro, i) => <article key={pro.name} className="pro-card"><div className="relative h-48 overflow-hidden rounded-[1.35rem]"><img src={pro.image} alt={pro.name} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-black/10"/><button onClick={() => setLiked(liked.includes(i) ? liked.filter((x) => x !== i) : [...liked, i])} aria-label="Favoritar" className="absolute right-3 top-3 rounded-full bg-black/35 p-2.5 backdrop-blur-md"><Heart size={16} fill={liked.includes(i) ? "#c6ff4a" : "none"} className={liked.includes(i) ? "text-[#c6ff4a]" : "text-white"}/></button><div className="absolute bottom-3 left-3 flex items-center gap-1.5 rounded-full bg-black/45 px-2.5 py-1 text-[10px] font-semibold backdrop-blur-md"><span className="h-1.5 w-1.5 rounded-full bg-[#c6ff4a]"/>{status[pro.status].label}</div></div><div className="px-1 pt-3"><div className="flex items-start justify-between"><div><h3 className="font-bold">{pro.name}</h3><p className="mt-0.5 text-xs text-white/45">{pro.specialty}</p></div><span className="rounded-lg bg-white/10 px-2 py-1 text-[10px] font-bold">★ 4.9</span></div><div className="mt-3 flex items-center gap-3 text-[11px] text-white/45"><span className="flex items-center gap-1"><MapPin size={12}/> {pro.distance}</span><span className="flex items-center gap-1"><Clock3 size={12}/> {pro.wait}</span></div></div></article>)}</div></section>
    <section className="mt-7 px-5"><div className="queue-card"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><span className="live-dot"/> <p className="elite-kicker text-[#c6ff4a]">Fila ao vivo</p></div><h2 className="mt-2 text-lg font-bold">Seu horário está chegando</h2><p className="mt-1 text-xs text-white/50">Lucas Barbeiro · senha #08</p></div><div className="text-right"><p className="text-3xl font-black text-[#c6ff4a]">03</p><p className="text-[10px] uppercase tracking-widest text-white/40">na sua frente</p></div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-[#c6ff4a]"/></div><div className="mt-4 flex items-center justify-between text-[11px] text-white/55"><span className="flex items-center gap-1.5"><Zap size={13} className="text-[#c6ff4a]"/> Chegue em até 18 min</span><button className="font-bold text-white">Acompanhar <ChevronRight className="inline" size={13}/></button></div></div></section>
    <nav className="elite-nav">{[{id:"início", icon:Home, label:"Início"},{id:"agenda",icon:CalendarDays,label:"Agenda"},{id:"mensagens",icon:MessageCircle,label:"Chat"},{id:"perfil",icon:UserRound,label:"Perfil"}].map(({id,icon:Icon,label}) => <button key={id} onClick={() => setActive(id)} className={active === id ? "active" : ""}><Icon size={19}/><span>{label}</span></button>)}</nav>
  </main>;
}
