import { useMemo, useState } from "react";
import { Bell, CalendarDays, ChevronRight, Clock3, Heart, Home, MapPin, MessageCircle, Search, SlidersHorizontal, UserRound, Zap } from "lucide-react";

const pros = [
  { name: "Lucas Barbeiro", specialty: "Fade & visagismo", distance: "0,8 km", status: "Disponível", wait: "15 min", image: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=900&q=85" },
  { name: "Studio Navalha", specialty: "Corte clássico", distance: "1,4 km", status: "Atendendo", wait: "25 min", image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=85" },
  { name: "Caio Visagista", specialty: "Barba premium", distance: "2,1 km", status: "Pausado", wait: "Reabre 14h", image: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=85" },
];

export function EliteClientApp() {
  const [active, setActive] = useState("Início");
  const [query, setQuery] = useState("");
  const [liked, setLiked] = useState<string[]>([]);
  const [joined, setJoined] = useState(false);
  const filtered = useMemo(() => pros.filter((pro) => pro.name.toLowerCase().includes(query.toLowerCase()) || pro.specialty.toLowerCase().includes(query.toLowerCase())), [query]);
  return <main className="elite-shell min-h-screen pb-28 text-white">
    <header className="flex items-center justify-between px-5 pb-5 pt-8"><div><p className="elite-kicker">Sua experiência, elevada</p><h1 className="mt-1 text-3xl font-black tracking-[-0.07em]">Olá, Gabriel<span className="text-[#c6ff4a]">.</span></h1><div className="mt-2 flex items-center gap-1.5 text-xs text-white/45"><MapPin size={13} className="text-[#c6ff4a]"/> Vila Madalena, São Paulo <ChevronRight size={13}/></div></div><button aria-label="Notificações" className="elite-icon"><Bell size={18}/><span/></button></header>
    <section className="flex gap-3 overflow-x-auto px-5 pb-6 [scrollbar-width:none]">{["Perto de mim","Mais bem avaliados","Novidades","Barba & cabelo"].map((label, i) => <button key={label} className="shrink-0 text-center"><div className="story-ring"><img src={["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80","https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80","https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80","https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=200&q=80"][i]} alt=""/></div><span className="mt-2 block text-[11px] text-white/60">{label}</span></button>)}</section>
    <section className="px-5"><div className="elite-search"><Search size={17}/><input aria-label="Buscar profissionais" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar profissionais, serviços..."/><button aria-label="Filtros" className="ml-auto rounded-xl bg-white/10 p-2"><SlidersHorizontal size={15}/></button></div></section>
    <section className="mt-7"><div className="flex items-end justify-between px-5"><div><p className="elite-kicker text-[#c6ff4a]">Agora perto de você</p><h2 className="mt-1 text-xl font-bold tracking-tight">Encontre seu próximo visual</h2></div><button className="text-xs font-semibold text-white/45">Ver mapa</button></div><div className="mt-4 flex gap-4 overflow-x-auto px-5 pb-2 [scrollbar-width:none]">{filtered.map((pro) => <article key={pro.name} className="pro-card"><div className="relative h-48 overflow-hidden rounded-[1.35rem]"><img src={pro.image} alt={pro.name} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-black/10"/><button onClick={() => setLiked(liked.includes(pro.name) ? liked.filter((x) => x !== pro.name) : [...liked, pro.name])} aria-label={`Favoritar ${pro.name}`} className="absolute right-3 top-3 rounded-full bg-black/35 p-2.5"><Heart size={16} fill={liked.includes(pro.name) ? "#c6ff4a" : "none"} className={liked.includes(pro.name) ? "text-[#c6ff4a]" : "text-white"}/></button><div className={`absolute bottom-3 left-3 flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold backdrop-blur-md ${pro.status === "Disponível" ? "bg-[#c6ff4a]/15 text-[#c6ff4a]" : pro.status === "Atendendo" ? "bg-amber-300/15 text-amber-200" : "bg-white/15 text-white/60"}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{pro.status}</div></div><div className="px-1 pt-3"><div className="flex items-start justify-between"><div><h3 className="font-bold">{pro.name}</h3><p className="mt-0.5 text-xs text-white/45">{pro.specialty}</p></div><span className="rounded-lg bg-white/10 px-2 py-1 text-[10px] font-bold">★ 4.9</span></div><div className="mt-3 flex items-center gap-3 text-[11px] text-white/45"><span className="flex items-center gap-1"><MapPin size={12}/> {pro.distance}</span><span className="flex items-center gap-1"><Clock3 size={12}/> {pro.wait}</span></div>{pro.status === "Disponível" && <button onClick={() => setJoined(true)} className="mt-3 w-full rounded-xl bg-[#c6ff4a] py-2.5 text-xs font-black text-black">{joined ? "Você está na fila" : "Entrar na fila virtual"}</button>}</div></article>)}</div></section>
    <section className="mt-7 px-5"><div className="queue-card"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><span className="live-dot"/> <p className="elite-kicker text-[#c6ff4a]">Fila ao vivo</p></div><h2 className="mt-2 text-lg font-bold">{joined ? "Você está quase lá" : "Seu horário está chegando"}</h2><p className="mt-1 text-xs text-white/50">Lucas Barbeiro · senha #{joined ? "11" : "08"}</p></div><div className="text-right"><p className="text-3xl font-black text-[#c6ff4a]">{joined ? "05" : "03"}</p><p className="text-[10px] uppercase tracking-widest text-white/40">na sua frente</p></div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full bg-[#c6ff4a] transition-all ${joined ? "w-[55%]" : "w-[72%]"}`}/></div><div className="mt-4 flex items-center justify-between text-[11px] text-white/55"><span className="flex items-center gap-1.5"><Zap size={13} className="text-[#c6ff4a]"/> Chegue em até {joined ? "24" : "18"} min</span><button className="font-bold text-white">Acompanhar <ChevronRight className="inline" size={13}/></button></div></div></section>
    <nav className="elite-nav">{[{id:"Início",icon:Home},{id:"Agenda",icon:CalendarDays},{id:"Chat",icon:MessageCircle},{id:"Perfil",icon:UserRound}].map(({id,icon:Icon}) => <button key={id} onClick={() => setActive(id)} className={active === id ? "active" : ""}><Icon size={19}/><span>{id}</span></button>)}</nav>
  </main>;
}

