import { useState } from "react";
import { ArrowUpRight, Bell, CalendarDays, Check, ChevronRight, Clock3, LayoutDashboard, MessageCircle, Pause, Play, Plus, UserRound, Wallet, X } from "lucide-react";

const clients = ["Rafael Mendes", "Bruno Costa", "João Pedro"];
const statuses = ["Disponível", "Atendendo", "Pausado", "Encerrado"];
export function EliteProfessionalApp() {
  const [status, setStatus] = useState("Disponível"); const [done, setDone] = useState<string[]>([]);
  return <main className="elite-shell min-h-screen pb-8 text-white"><header className="flex items-center justify-between px-5 pb-6 pt-8"><div><p className="elite-kicker text-[#c6ff4a]">Cockpit profissional</p><h1 className="mt-1 text-3xl font-black tracking-[-0.07em]">Bom dia, Lucas<span className="text-[#c6ff4a]">.</span></h1></div><button aria-label="Alertas" className="elite-icon"><Bell size={18}/><span/></button></header>
  <section className="px-5"><div className="status-panel"><div className="flex items-start justify-between"><div><p className="text-xs text-white/45">Seu status agora</p><h2 className="mt-1 text-2xl font-black">{status}</h2></div><span className="live-dot mt-2"/></div><div className="mt-4 grid grid-cols-2 gap-2">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`status-toggle justify-center ${status === item ? "on" : ""}`}>{item === "Disponível" ? <Play size={14}/> : item === "Pausado" ? <Pause size={14}/> : item === "Atendendo" ? <Clock3 size={14}/> : <X size={14}/>} {item}</button>)}</div><div className="mt-5 grid grid-cols-3 gap-2"><div><strong>32</strong><span>atendidos</span></div><div><strong>R$ 840</strong><span>receita hoje</span></div><div><strong>24m</strong><span>tempo médio</span></div></div></div></section>
  <section className="mt-7 px-5"><div className="section-heading"><div><p className="elite-kicker">Operação ao vivo</p><h2 className="mt-1 text-xl font-bold">Filas de atendimento</h2></div><button className="rounded-full bg-[#c6ff4a] px-3 py-2 text-xs font-black text-black"><Plus size={14} className="mr-1 inline"/> Adicionar</button></div><div className="grid grid-cols-2 gap-3"><div className="queue-card"><p className="elite-kicker text-[#c6ff4a]">Presencial</p><strong className="mt-2 block text-3xl">08</strong><span className="text-[11px] text-white/45">aguardando na loja</span><div className="mt-4 space-y-2"><span className="queue-badge current block">#01 · Rafael</span><span className="queue-badge block">#02 · Bruno</span></div></div><div className="queue-card"><p className="elite-kicker text-[#c6ff4a]">Encaixe virtual</p><strong className="mt-2 block text-3xl">05</strong><span className="text-[11px] text-white/45">clientes online</span><div className="mt-4 space-y-2"><span className="queue-badge current block">#11 · Camila</span><span className="queue-badge block">#12 · Diego</span></div></div></div></section>
  <section className="mt-7 px-5"><div className="section-heading"><div><p className="elite-kicker">Próximos clientes</p><h2 className="mt-1 text-xl font-bold">Sua agenda inteligente</h2></div><button className="text-xs font-semibold text-[#c6ff4a]">Ver agenda <ArrowUpRight className="inline" size={13}/></button></div><div className="space-y-2">{clients.map((name, i) => <div key={name} className="client-row"><div className="grid h-10 w-10 place-items-center rounded-full bg-white/10 text-sm font-bold">{name.split(" ").map((n) => n[0]).join("")}</div><div className="min-w-0 flex-1"><p className="font-bold">{name}</p><p className="text-[11px] text-white/40">{i === 0 ? "Agora · Fade + barba" : `${15 + i * 15} min · Corte clássico`}</p></div>{done.includes(name) ? <span className="queue-badge current"><Check size={13}/></span> : <button onClick={() => setDone([...done, name])} className="rounded-lg bg-white/10 px-2 py-2 text-[10px] font-bold">{i === 0 ? "Chamar" : "Iniciar"}</button>}</div>)}</div></section>
  <section className="mt-7 px-5"><div className="agenda-card"><div className="flex items-center justify-between"><div><p className="elite-kicker text-[#c6ff4a]">Hoje · 09 setembro</p><h2 className="mt-1 text-lg font-bold">Agenda otimizada</h2></div><CalendarDays className="text-[#c6ff4a]" size={20}/></div><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-3 text-xs text-white/55"><span>Próximo horário livre</span><b className="text-white">16:40</b><button className="text-[#c6ff4a]">Abrir vaga</button></div></div></section>
  <nav className="mt-8 flex justify-around border-t border-white/10 px-5 pt-5 text-white/35">{[[LayoutDashboard,"Painel"],[CalendarDays,"Agenda"],[MessageCircle,"Chat"],[Wallet,"Financeiro"],[UserRound,"Perfil"]].map(([Icon,label]) => <button key={String(label)} className={label === "Painel" ? "text-[#c6ff4a]" : ""}><Icon size={18}/><span className="mt-1 block text-[9px]">{label}</span></button>)}</nav></main>;
}
