/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ApiPublicQuickReplyRouteImport } from './routes/api/public/quick-reply'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuickReplyRoute = ApiPublicQuickReplyRouteImport.update({
  id: '/api/public/quick-reply',
  path: '/api/public/quick-reply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/painel': typeof PainelRoute
  '/api/public/quick-reply': typeof ApiPublicQuickReplyRoute
}
export interface FileRoutesByTo {
  '/painel': typeof PainelRoute
  '/api/public/quick-reply': typeof ApiPublicQuickReplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/painel': typeof PainelRoute
  '/api/public/quick-reply': typeof ApiPublicQuickReplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/painel' | '/api/public/quick-reply'
  fileRoutesByTo: FileRoutesByTo
  to: '/painel' | '/api/public/quick-reply'
  id: '__root__' | '/painel' | '/api/public/quick-reply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PainelRoute: typeof PainelRoute
  ApiPublicQuickReplyRoute: typeof ApiPublicQuickReplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quick-reply': {
      id: '/api/public/quick-reply'
      path: '/api/public/quick-reply'
      fullPath: '/api/public/quick-reply'
      preLoaderRoute: typeof ApiPublicQuickReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PainelRoute: PainelRoute,
  ApiPublicQuickReplyRoute: ApiPublicQuickReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
